apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
  annotations:
    {{- include "mychart.annotations" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: 172.16.253.6
  clusterIPs:
  - 172.16.253.6
  externalTrafficPolicy: Cluster
  ports:
  - name: 8000-8000-tcp
    nodePort: {{ .Values.service.nodePort }}
    port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "mychart.selectorLabels" . | nindent 4 }}
